# CMake generated Testfile for 
# Source directory: C:/plms/galanthus/mark2haru
# Build directory: C:/plms/galanthus/mark2haru/build-vs-cleanup
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_render_neutral_brief]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Debug/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/neutral_brief.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf")
  set_tests_properties([=[smoke_render_neutral_brief]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;142;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_render_neutral_brief]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Release/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/neutral_brief.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf")
  set_tests_properties([=[smoke_render_neutral_brief]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;142;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smoke_render_neutral_brief]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/MinSizeRel/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/neutral_brief.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf")
  set_tests_properties([=[smoke_render_neutral_brief]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;142;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_render_neutral_brief]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/RelWithDebInfo/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/neutral_brief.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf")
  set_tests_properties([=[smoke_render_neutral_brief]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;142;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
else()
  add_test([=[smoke_render_neutral_brief]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_check_neutral_brief_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_neutral_brief_header]=] PROPERTIES  DEPENDS "smoke_render_neutral_brief" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;148;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_check_neutral_brief_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_neutral_brief_header]=] PROPERTIES  DEPENDS "smoke_render_neutral_brief" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;148;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smoke_check_neutral_brief_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_neutral_brief_header]=] PROPERTIES  DEPENDS "smoke_render_neutral_brief" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;148;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_check_neutral_brief_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/neutral_brief.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_neutral_brief_header]=] PROPERTIES  DEPENDS "smoke_render_neutral_brief" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;148;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
else()
  add_test([=[smoke_check_neutral_brief_header]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_render_western_european]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Debug/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/western_european.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf")
  set_tests_properties([=[smoke_render_western_european]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;158;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_render_western_european]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Release/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/western_european.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf")
  set_tests_properties([=[smoke_render_western_european]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;158;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smoke_render_western_european]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/MinSizeRel/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/western_european.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf")
  set_tests_properties([=[smoke_render_western_european]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;158;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_render_western_european]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/RelWithDebInfo/mark2haru.exe" "C:/plms/galanthus/mark2haru/examples/western_european.md" "C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf")
  set_tests_properties([=[smoke_render_western_european]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;158;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
else()
  add_test([=[smoke_render_western_european]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_check_western_european_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_western_european_header]=] PROPERTIES  DEPENDS "smoke_render_western_european" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;164;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_check_western_european_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_western_european_header]=] PROPERTIES  DEPENDS "smoke_render_western_european" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;164;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smoke_check_western_european_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_western_european_header]=] PROPERTIES  DEPENDS "smoke_render_western_european" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;164;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_check_western_european_header]=] "C:/Program Files/CMake/bin/cmake.exe" "-DPDF=C:/plms/galanthus/mark2haru/build-vs-cleanup/western_european.pdf" "-P" "C:/plms/galanthus/mark2haru/cmake/check_pdf_header.cmake")
  set_tests_properties([=[smoke_check_western_european_header]=] PROPERTIES  DEPENDS "smoke_render_western_european" _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;164;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
else()
  add_test([=[smoke_check_western_european_header]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[png_roundtrip]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Debug/test_png.exe")
  set_tests_properties([=[png_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;175;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[png_roundtrip]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/Release/test_png.exe")
  set_tests_properties([=[png_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;175;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[png_roundtrip]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/MinSizeRel/test_png.exe")
  set_tests_properties([=[png_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;175;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[png_roundtrip]=] "C:/plms/galanthus/mark2haru/build-vs-cleanup/RelWithDebInfo/test_png.exe")
  set_tests_properties([=[png_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/plms/galanthus/mark2haru/CMakeLists.txt;175;add_test;C:/plms/galanthus/mark2haru/CMakeLists.txt;0;")
else()
  add_test([=[png_roundtrip]=] NOT_AVAILABLE)
endif()
